### ISSUE TITLE
Missing Type definitions

### ISSUE THREAD

**Issue by jonahtwalker** [bitpay/nodejs-bitpay-client#17]
I haven't been able to find the type definitions available anywhere online. Can the `*.d.ts` file be supplied in the package?

**Comment by shadowbrush** [comment]
This should fix it: https://github.com/bitpay/nodejs-bitpay-client/pull/19

**Comment by jekh** [comment]
#19 didn't fix the issue entirely. I created a PR with a simple fix for the remaining types: https://github.com/bitpay/nodejs-bitpay-client/pull/37

**Comment by anbugal** [comment]
this should be fixed in the next version 2.0.2112
